version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
    volumes:
      - config:/config
    ports:
      - 8085:80
    restart: unless-stopped

volumes:
  config:
