version: '3.3'

services:
  traefik:
    image: traefik:v2.5
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8888:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml
      - source: traefik-dynamic.yml
        target: /etc/traefik/traefik-dynamic.yml
    environment:
      - DUCKDNS_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SUBDOMAINS}.duckdns.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=default"

  duckdns:
    image: linuxserver/duckdns
    environment:
      - TZ=Europe/Oslo
      - SUBDOMAINS
      - TOKEN=${DUCKDNS_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  web:
    external:
      name: web

configs:
  traefik.yml:
    external:
      name: traefik.yml
  traefik-dynamic.yml:
    external:
      name: traefik-dynamic.yml

volumes:
  letsencrypt:
